// @ts-nocheck
// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.
import { clientsClaim } from "workbox-core";
import { RouteHandler } from "workbox-core/types.js";
import { ExpirationPlugin } from "workbox-expiration";
import { createHandlerBoundToURL, precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { CacheFirst, StaleWhileRevalidate } from "workbox-strategies";

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
	// Return false to exempt requests from being fulfilled by index.html.
	({ request, url }) => {
		// If this isn't a navigation, skip.
		if (request.mode !== "navigate") {
			return false;
		} // If this is a URL that starts with /_, skip.

		if (url.pathname.startsWith("/_")) {
			return false;
		} // If this looks like a URL for a resource, because it contains // a file extension, skip.

		if (url.pathname.match(fileExtensionRegexp)) {
			return false;
		} // Return true to signal that we want to use the handler.

		return true;
	},
	createHandlerBoundToURL("/index.html")
);

const matchFileExtensions = (fileExtensions: string[]) => {
	return new RegExp(`.*(${fileExtensions.join("|")})$`);
};

const createFileCache = (fileExtensions: string[], handler: RouteHandler) => {
	return registerRoute(
		({ url }) =>
			url.origin === self.location.origin &&
			url.pathname.match(matchFileExtensions(fileExtensions)),
		handler
	);
};

// Cache fonts (heavily, since they won't change very often).
createFileCache(
	[".ttf", ".otf", ".woff", ".woff2"],
	new CacheFirst({
		cacheName: "fonts",
		plugins: [new ExpirationPlugin({ maxEntries: 20 })]
	})
);

// Cache images.
createFileCache(
	[".png", ".jpg", ".jpeg", ".svg"],
	new StaleWhileRevalidate({
		cacheName: "images",
		plugins: [
			// Ensure that once this runtime cache reaches a maximum size the
			// least-recently used images are removed.
			new ExpirationPlugin({ maxEntries: 10_000 })
		]
	})
);

// Cache the last n tracks' cover images
const trackCoversToCacheRegex = new RegExp(`.*\/cover/(50|600)$`);
registerRoute(
	({ url }) => url.pathname.match(trackCoversToCacheRegex),
	new CacheFirst({
		cacheName: "tracks-covers",
		plugins: [
			// Ensure that once this runtime cache reaches a maximum size the
			// least-recently used images are removed.
			new ExpirationPlugin({ maxEntries: 10_000 })
		]
	})
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
	if (event.data && event.data.type === "SKIP_WAITING") {
		self.skipWaiting();
	}
});
